name: CI

on: [push]

jobs:
  build-tvos:
    name: tvOS

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3.0.0
    
    - uses: actions/cache@v3
      name: "Get cache"
      with:
        path: ~/Library/Developer/Xcode/DerivedData/PopcornTorrent*
        key: ${{ runner.os }}-cache
        restore-keys: |
            ${{ runner.os }}-cache
                
    - name: "Run Tests"
      run: |
        xcodebuild \
        -scheme PopcornTorrent \
        -destination "platform=tvOS Simulator,OS=16.0,name=Apple TV" \
        -resultBundlePath TestResults \
        test
        
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
      # ^ This is important because the action will be run
      # even if the test fails in the previous step.
