name: CI

on: [push]

jobs:
  build-tvos:
    name: tvOS

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3.0.0
                
    - name: "Run Tests"
      run: |
        xcodebuild \
        -scheme PopcornTorrent \
        -destination "platform=tvOS Simulator,OS=16.1,name=Apple TV" \
        test
